// Maps an exercise slug to its bundled grimdark art (generated by
// scripts/gen_art.py). Vite resolves each WebP to a hashed, cache-busted URL at
// build time and bundles it into the deploy, so the images ship with the app —
// no Supabase storage or runtime fetch needed.

const modules = import.meta.glob('@/assets/exercises/*.webp', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

const bySlug: Record<string, string> = {}
for (const [path, url] of Object.entries(modules)) {
  const slug = path.split('/').pop()!.replace(/\.webp$/, '')
  bySlug[slug] = url
}

/** Returns the bundled art URL for an exercise slug, or undefined if none. */
export function getExerciseArt(slug: string | null | undefined): string | undefined {
  if (!slug) return undefined
  return bySlug[slug]
}

/** Whether bundled art exists for the given slug. */
export function hasExerciseArt(slug: string | null | undefined): boolean {
  return !!slug && slug in bySlug
}
