// Bundled grimdark UI background art (generated by `gen_art.py --ui`). Vite
// resolves each to a hashed URL at build time and ships them with the app.
import streakBanner from '@/assets/ui/streak_banner.webp'
import plannedWorkout from '@/assets/ui/planned_workout.webp'
import restDay from '@/assets/ui/rest_day.webp'
import navFrame from '@/assets/ui/nav_frame.webp'

export const uiArt = {
  streakBanner,
  plannedWorkout,
  restDay,
  navFrame,
} as const
